name: regeneate incubation listing

on:
  schedule:
    - cron: "*/60 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: node generator.js
      - uses: stefanzweifel/git-auto-commit-action@v4
