name: regeneate incubation listing

on:
  push:
    branches:
    - gh-pages
  schedule:
    - cron: "*/60 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: node generator.js
        env:
          WICG_TOKEN: ${{ secrets.WICG_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
