name: regeneate incubation listing

on:
  schedule:
    - cron: "*/60 * * * *"
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Run a one-line script
      - uses: actions/checkout@v3
      - run: npm i
      - run: node generator.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: regenerated repo.json"
          
